[project]
name = "ollama-tools"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aisuite[ollama]>=0.1.6",
    "beautifulsoup4>=4.12.3",
    "ollama>=0.4.4",
    "openai>=1.57.2",
    "requests>=2.32.3",
]
